# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "deploy firebase"
  lane :distribute do
    gradle(task: "clean assembleRelease")
    firebase_app_distribution(
        service_credentials_file: "secret/uwang-db913-6be6db44a038.json",
        app: "1:616208190167:android:21914953259000a938fe92",
        release_notes_file: "FirebaseDistributionConfig/release_notes.txt",
        groups_file: "FirebaseDistributionConfig/groups.txt",
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
